# Generated by Django 4.2 on 2023-05-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_recipe_category_recipe_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
