# Generated by Django 4.2 on 2023-05-16 12:00

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='hashtags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=8192, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=8192, null=True), size=None),
        ),
    ]
