# Generated by Django 4.2 on 2023-05-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
